version: '3.9'
services:
  mage:
    image: mageai/mageai:latest
    container_name: magic
    command: mage start dew1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PG_HOST_PORT: ${PG_HOST_PORT}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ~/.minio:/root/.minio
      - shared-jars:/opt/mage/jars
    restart: on-failure:5

  trino:
    hostname: trino
    image: 'trinodb/trino:410'
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
      - ./etc/catalog:/etc/trino/catalog
    depends_on:
      - hive-metastore

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb

  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} 
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY} 
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}

  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "7077:7077"
      - "8081:8080"  
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_UI_PORT=8081
      - JAVA_HOME=/opt/bitnami/java 
    volumes:
      - shared-jars:/opt/bitnami/spark/jars

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - JAVA_HOME=/opt/bitnami/java  
    volumes:
      - shared-jars:/opt/bitnami/spark/jars

volumes:
  minio-data:
    driver: local
  shared-jars:
    driver: local
